.\" `groff -mspdf` document
.so /home/hos/.config/groff/settings.ms
.so /home/hos/.config/groff/macros.ms
.fam T\" font-family {T:serif, H:sans, C:code},
.\".\" first Page {{{
.\".RP no
.\".TL
.\"Title
.\".AU
.\"Author
.\".AI
.\"Institution
.\".AB
.\"This is the Abstract Section.
.\".AE
.\".\" }}}
.\".\" page header/footer {{{
.\".ds RH Author\" author name on top-left
.\".ds LH Title\" title on top-center
.\".ds CF \*(DY\" current date on top-right
.\".\" }}}

.\" body

.\".TC
