metadata:
  keywords:
    - 'English Document'

verbosity: WARNING # INFO
top-level-division: section # part, chapter
toc: false
number-sections: false

pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/highlight/monochrome.theme
#highlight-style: /home/hos/.config/pandoc/highlight/solarized-light.theme

variables:
  geometry: margin=1in
  header-includes:
    - \usepackage{/home/hos/.config/pandoc/defaults/english/main}
filters:
    - /home/hos/.config/pandoc/filters/tex-codeblock-en.lua
    - /home/hos/.config/pandoc/filters/en-date.lua
    - /home/hos/.config/pandoc/filters/tex-quoteblock-en.lua
