" __     ___
" \ \   / (_)_ __ ___
"  \ \ / /| | '_ ` _ \
"   \ V / | | | | | | |
"    \_/  |_|_| |_| |_|
"
" Main Section:
source ~/.vim/modules/main.vim
"
" Separate Tty And Terminal:
if has("gui_running")
	set nowrap
	colorscheme hybrid
	source ~/.vim/modules/status.vim
	source ~/.vim/modules/extra.vim
	set cursorline
	set nu
	set nolist
	set guifont=Source\ Code\ Pro\ Medium\ 16
elseif empty($DISPLAY)
	" TTY:
	set nolist
	colorscheme desert
	set nocursorline
else
	" Terminal:
	source ~/.vim/modules/simplestatus.vim
	set ls=0
	set showtabline=0
	set cursorline
"	set nu
	" Colorschemes:
	"solarized minimalist 256_noir codedark
	"sunbather hybrid xcodedarkhc gruvbox
	colorscheme 256_noir
endif
"
hi SpecialKey ctermbg=NONE guibg=NONE

" Keybinding:
source ~/.vim/modules/keybinds.vim
"
" Netrw:
source ~/.vim/modules/netrw.vim
"
" Skel Files:
source ~/.vim/modules/skels.vim
"
" Compile Section
source ~/.vim/modules/oldcp.vim
"
" Take Note
source ~/.vim/modules/Note.vim
"
" Scpecial Characters
source ~/.vim/modules/abreviation.vim
"
" Define Sent Filetype:
au FileType sent source ~/.vim/modules/sent.vim
"
" add some extra features + plugins (commented out)
source ~/.vim/modules/extra.vim
"
" Build notes from one script of mine (if you don's know or use it, just comment it out)
source ~/.vim/modules/Note.vim
"
"highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212
"autocmd InsertEnter * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=234 guifg=NONE guibg=#1c1c1c
"autocmd InsertLeave * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212

"autocmd VimEnter * nested
"\ if !argc() && (line2byte('$') == -1) && (v:progname =~? '^[-gmnq]\=vim\=x\=\%\$')
"\ | if get(g:, 'startify_session_autoload') && filereadable('Session.vim')
"\ | source ~/.vim/modules/session.vim
"\ | else
"\ | call startify#insane_in_the_membrane()
"\ | endif
"\ | endif
"\ | autocmd! startify VimEnter
"source ~/.vim/modules/session.vim
