metadata:
    keywords:
        - 'Theme for beamer'
pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/highlight/solarized-dark.theme

variables:
    background-image: /home/hos/.config/pandoc/beamer/bg/Shiny-Black-PPT-Backgrounds.jpg
    linkcolor: draculapink
    filecolor: draculagreen
    citecolor: draculapurple
    urlcolor: draculacyan
    toccolor: draculaorange
    header-includes:
        - \usepackage{/home/hos/.config/pandoc/dracula/theme}
        - \usepackage{/home/hos/.config/pandoc/beamer/main}

        - \usetheme{Copenhagen}
        - \usecolortheme{albatross}
        - \setbeamercolor*{palette primary}{use=structure,fg=white,bg=draculacl}
        - \setbeamercolor{titlelike}{parent=palette primary,fg=draculapurple}
        - \setbeamercolor{block}{parent=palette primary,fg=draculapurple}
        - \setbeamercolor{author in head/foot}{bg=UBCblue,fg=white}
