metadata:
    keywords:
        - 'Persian beamer config'

pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/highlight/solarized-light-beamer.theme

variables:
#    background-image: /home/hos/.config/pandoc/background/Beautiful-Minimalist-Presentation.jpg
#    background-image: /home/hos/.config/pandoc/background/bmpim.jpg
    header-includes:
        - \usepackage{/home/hos/.config/pandoc/beamer/persian}
