metadata:
  keywords:
    - 'Persian Document'

number-sections: false
pdf-engine: xelatex
#highlight-style: /home/hos/.config/pandoc/highlight/dracula.theme
#highlight-style: tango
highlight-style: /home/hos/.config/pandoc/highlight/solarized-light.theme

variables:
  geometry: margin=1in
#  linkcolor: draculapink
#  filecolor: draculagreen
#  citecolor: draculapurple
#  urlcolor:  draculacyan
#  toccolor:  draculaorange
  header-includes:
    - \usepackage{/home/hos/.config/pandoc/defaults/persian/main}
#    - \usepackage{/home/hos/.config/pandoc/dracula/theme}
#    - \pagecolor{draculabg}
#    - \color{draculafg}
filters:
    - /home/hos/.config/pandoc/filters/fa-date.lua
    - /home/hos/.config/pandoc/filters/tex-codeblock-fa.lua
    - /home/hos/.config/pandoc/filters/tex-quoteblock-fa.lua
