metadata:
  keywords:
    - 'Persian Document'

number-sections: false
pdf-engine: xelatex
#highlight-style: /home/hos/.config/pandoc/highlight/dracula.theme
highlight-style: /home/hos/.config/pandoc/highlight/solarized-light.theme

variables:
  geometry: margin=1in
  linkcolor: draculapink
  filecolor: draculagreen
  citecolor: draculapurple
  urlcolor:  draculacyan
  toccolor:  draculaorange
  header-includes:
    - \usepackage{/home/hos/.config/pandoc/persian/main}
    #- \usepackage{/home/hos/.config/pandoc/dracula/theme}
    #- \pagecolor{draculabg}
    #- \color{draculafg}
