metadata:
  keywords:
    - 'Nord theme for beamer'
pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/dracula/dracula.theme

variables:
  linkcolor: draculapink
  filecolor: draculagreen
  citecolor: draculapurple
  urlcolor: draculacyan
  toccolor: draculaorange
  header-includes:
    - \usetheme{Nord}
    - \usecolortheme{Nord}
    #- \usepackage{/home/hos/.config/pandoc/dracula/beamercolorthemedracula}
    - \usepackage{/home/hos/.config/pandoc/dracula/beamer}
