metadata:
    keywords:
        - 'Theme for beamer'
pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/highlight/dracula-beamer.theme

variables:
    background-image: /home/hos/.config/pandoc/background/manjaro-default-adapta-lockscreen.jpg
    header-includes:
        - \usepackage{/home/hos/.config/pandoc/defaults/beamer/en-manjaro}
filters:
    - /home/hos/.config/pandoc/filters/en-date.lua
