metadata:
    keywords:
        - 'Persian light (ubuntu) beamer theme '
    documentclass: beamer
pdf-engine: xelatex
highlight-style: /home/hos/.config/pandoc/highlight/solarized-light-beamer.theme
variables:
    aspectratio: 169
    background-image: /home/hos/.config/pandoc/background/Beautiful-Minimalist-Presentation.jpg
    header-includes:
        - \usepackage{/home/hos/.config/pandoc/defaults/beamer/fa-ubuntu}
filters:
    - /home/hos/.config/pandoc/filters/fa-today.lua
    - /home/hos/.config/pandoc/filters/tex-beamer-codeblock-fa.lua
